service: aws-nodejs-membership-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 5
  endpointType: regional
  environment:
    NODE_PATH: '/:/opt/node_modules'
    IS_OFFLINE: ${self:custom.isOffline}
    CONFIG_USER_TABLE: ${self:custom.UserTable.name}
    CONFIG_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-url}
    HASH_KEY_PREFIX_USER: user_
    SORT_KEY_USER_VALUE: profile
    HASH_KEY_PREFIX_MEMBERSHIP: membership_
    SORT_KEY_MEMBERSHIP_VALUE: meta
    SORT_KEY_PREFIX_MEMBERSHIP_MEMBER: membershipMember_
    SORT_KEY_PREFIX_MEMBERSHIP_EVENT: event_
  iamRoleStatements:
    - ${file(resources/iam/iamMembershipTable.yml):MembershipTableIAM}
custom:
  UserTable:
    arn: !GetAtt UserTable.Arn
    name: !Ref UserTable
  offlineTableName:
    membership: 'aige-membership'
  endpoints:
    dynamodb-url: 'http://localhost:8000'
  isOffline: false
  dynamodb:
    start:
      migrate: true
      seed: true
    stages:
      - dev
    seed:
      domain:
        sources:
          - table:  ${self:custom.offlineTableName.membership}-${self:provider.stage}
            rawsources: [./testdata/seeddata/aige-user.json]

functions:
  - ${file(resources/lambda/user/lambdas.yml)}
 # - ${file(resources/lambda/membershipMember/lambdas.yml)}
 # - ${file(resources/lambda/membership/lambdas.yml)}
 # - ${file(resources/lambda/event/lambdas.yml)}
resources:
  Resources:
    UserTable: ${file(resources/dynamodb/user/dynamodb.yml):UserTable}

layers:
  MiddyDependencies:
    path: middy-layer
    description: Middy libraries
    package:
      include:
        - node_modules/**
package:
  exclude:
    - .dynamodb/**
    - .serverless/**
    - middy-layer/**
    - testdata/**
    - testqueries/**

plugins:
  - serverless-dynamodb-local
  - serverless-pseudo-parameters
  - serverless-offline # should be last in list
