#

service: aws-nodejs-membership-api

package:
  exclude:
    - .dynamodb/**
    - node_modules/**
  include:
    - node_modules/underscore/**
    - node_modules/uuid/**

plugins:
  - serverless-dynamodb-local
  - serverless-offline # should be last in list

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: prod
  memorySize: 128
  timeout: 5
  endpointType: regional

functions:
  hello:
    handler: handler.hello
    description: Say Hello
    events:
      - http:
          path: hello
          method: get
          cors: true
