
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: aige-membership-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: admission_date
          AttributeType: N
        - AttributeName: event_status
          AttributeType: S
        - AttributeName: ending_date
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE


      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

      GlobalSecondaryIndexes:
        - IndexName: GSI1_SK_admission_date
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: admission_date
              KeyType: RANGE

          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1


        - IndexName: statusEndingDate-Index
          KeySchema:
            - AttributeName: event_status
              KeyType: HASH
            - AttributeName: ending_date
              KeyType: RANGE

          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
