
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: aige-membership-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: admission_date
          AttributeType: S
        - AttributeName: season_date
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE


      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

      GlobalSecondaryIndexes:
        - IndexName: GSI1_SK_admission_date
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: admission_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

        - IndexName: GSI1_SK_season_date
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: season_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
