
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: aige-membership-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: admission_year
          AttributeType: N
        - AttributeName: season_year
          AttributeType: N

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE


      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

      GlobalSecondaryIndexes:
        - IndexName: GSI_SK_admission_year
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: admission_year
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

        - IndexName: GSI_SK_season_year
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: season_year
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

        - IndexName: GSI_PK_season_year
          KeySchema:
            - AttributeName: season_year
              KeyType: HASH
            - AttributeName: SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
